# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-27 16:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0002_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'permissions': (('can_view_others', 'Can veiw others shifts and events'),)},
        ),
    ]
