# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-29 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0003_auto_20161227_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event',
            field=models.CharField(choices=[('IN', 'Clock in'), ('OUT', 'Clock out'), ('BST', 'Break start'), ('BEN', 'Break end')], max_length=3),
        ),
    ]
